'use strict';

/* ============================================================
   script.js — Agrinho 2026
   Projeto: Colégio Estadual Vinícius de Morais (PR)
   Funcionalidades:
     - Tradução PT / EN / ES
     - Temas de acessibilidade (Padrão / L/W / D/B)
     - Controle de tamanho de fonte
     - Narração com Web Speech API
     - Contador global de apoios com Firebase Firestore
     - Menu mobile responsivo
     - Formulário de sugestão com validação
     - Animação de entrada por scroll (IntersectionObserver)
   ============================================================ */

/* ============================================================
   DICIONÁRIO DE TRADUÇÕES
   ============================================================ */

var TRADUCOES = {

  /* ---- PORTUGUÊS ------------------------------------------ */
  pt: {
    page_title:        'Agrinho 2026 — Agro Forte, Futuro Sustentável',
    label_idioma:      'Idioma:',
    label_visual:      'Visual:',
    label_texto:       'Texto:',
    label_audio:       'Áudio:',
    btn_colorido:      'Padrão',
    btn_branco:        'L/W',
    btn_preto:         'D/B',
    btn_narrar:        'Narrar Site',
    btn_parar:         'Parar Narração',
    logo_titulo:       'Agrinho 2026',
    logo_subtitulo:    'SENAR · Paraná',
    nav_sobre:         'Sobre',
    nav_tema:          'Tema',
    nav_tecnologias:   'Tecnologias',
    nav_video:         'Vídeo',
    nav_apoio:         'Apoiar',
    nav_contato:       'Contato',
    hero_eyebrow:      'Concurso Agrinho 2026',
    hero_titulo:       'Agro forte,\nfuturo sustentável',
    hero_subtitulo:    'Equilíbrio entre produção e meio ambiente',
    hero_btn_conhecer: 'Conhecer o Projeto',
    hero_btn_apoiar:   'Apoiar Agora',
    sobre_eyebrow:     'O Programa',
    sobre_titulo:      'O que é o Agrinho?',
    sobre_p1:          'O Programa Agrinho é uma iniciativa do SENAR Paraná que existe há mais de 25 anos, conectando a educação do campo e da cidade por meio de temas como saúde, cidadania e, nesta edição, sustentabilidade agrícola.',
    sobre_p2:          'Em 2026, o tema convida estudantes a refletirem sobre como o agronegócio brasileiro pode ser economicamente forte sem comprometer os recursos naturais para as próximas gerações. Tecnologia, consciência e responsabilidade caminham juntas.',
    sobre_p3:          'Este site foi criado como projeto de participação do Colégio Estadual Vinícius de Morais (PR), explorando conceitos de produção sustentável, inovação tecnológica no campo e o papel de cada cidadão na construção de um futuro mais verde.',
    estat_anos:        'Anos de Programa',
    estat_municipios:  'Municípios Participantes',
    estat_alunos:      'Alunos Impactados',
    tema_eyebrow:      'O Desafio',
    tema_titulo:       'Produção e Natureza em Equilíbrio',
    tema_intro:        'O Brasil é um dos maiores produtores de alimentos do mundo. Mas como garantir que essa produção respeite o planeta? Três pilares sustentam essa resposta:',
    pilar1_titulo:     'Agropecuária Responsável',
    pilar1_desc:       'Práticas como o plantio direto, rotação de culturas e integração lavoura-pecuária-floresta reduzem a erosão do solo, poupam água e aumentam a produtividade ao mesmo tempo.',
    pilar2_titulo:     'Economia Circular',
    pilar2_desc:       'Resíduos agrícolas como palha e esterco viram energia, compostagem e biofertilizantes. Nada se perde: tudo se transforma em mais produção com menos impacto ambiental.',
    pilar3_titulo:     'Cidadania Ambiental',
    pilar3_desc:       'O campo precisa de guardiões. Desde a escola, cada aluno aprende que escolhas de consumo, descarte correto do lixo e preservação de nascentes são atos de cidadania concreta.',
    tec_eyebrow:       'Inovação no Campo',
    tec_titulo:        'Tecnologias Sustentáveis',
    tec_intro:         'O agricultor moderno conta com ferramentas que antes pareciam ficção científica. Veja três exemplos que já transformam o agro brasileiro:',
    drone_credito:     'Foto: Pexels / Foto de Drone Agricola',
    drone_titulo:      'Agricultura de Precisão com Drones',
    drone_desc:        'Drones equipados com câmeras multiespectrais sobrevoam as lavouras e identificam áreas com deficiência nutricional, pragas ou estresse hídrico com precisão de centímetros. Isso permite que o produtor aplique insumos somente onde é necessário, reduzindo o uso de defensivos em até 40% e economizando água e combustível. O resultado é uma lavoura mais saudável e um ambiente mais preservado.',
    irri_credito:      'Foto: Pexels / Foto de Irrigacao por Gotejamento',
    irrigacao_titulo:  'Irrigação Inteligente por Gotejamento',
    irri_desc:         'O sistema de irrigação por gotejamento entrega água diretamente na raiz da planta, gota a gota, controlado por sensores de umidade do solo conectados à internet. Sensores monitoram em tempo real a necessidade hídrica de cada espécie e irrigam apenas quando necessário. Comparado à irrigação convencional por aspersão, o gotejamento inteligente economiza até 60% de água, um recurso vital cada vez mais escasso no planeta.',
    solar_credito:     'Foto: Pexels / Foto de Energia Solar Rural',
    solar_titulo:      'Energia Solar Fotovoltaica Rural',
    solar_desc:        'Painéis solares instalados em propriedades rurais geram eletricidade limpa diretamente do sol, eliminando ou reduzindo drasticamente a conta de energia de fazendas e sítios. A energia excedente pode ser injetada na rede elétrica, gerando créditos ao produtor. Com o custo dos painéis caindo mais de 80% na última década, a energia solar se tornou um dos investimentos mais inteligentes e sustentáveis para o agricultor brasileiro do século XXI.',
    video_eyebrow:     'Assista',
    video_titulo:      'O Campo em Movimento',
    video_intro:       'Veja a beleza e a força do agronegócio sustentável através das imagens abaixo.',
    video_credito:     'Video por: Fernando Sanchez Aranguren (Pexels)',
    video_fallback:    'Seu navegador não suporta a reprodução de vídeo HTML5.',
    apoio_eyebrow:     'Participe',
    apoio_titulo:      'Apoie Este Projeto',
    apoio_intro:       'Acredita num agro mais sustentável? Demonstre seu apoio clicando abaixo!',
    apoio_contador:    'Este projeto já recebeu {N} apoios!',
    apoio_carregando:  'Carregando apoios...',
    apoio_btn:         'Apoiar Projeto',
    apoio_ja_feito:    'Você já registrou seu apoio. Obrigado!',
    apoio_registrando: 'Registrando apoio...',
    apoio_erro:        'Não foi possível registrar o apoio. Tente novamente.',
    contato_eyebrow:   'Fale Conosco',
    contato_titulo:    'Deixe sua Sugestão',
    contato_intro:     'Tem uma ideia para tornar o projeto ainda melhor? Compartilhe com a gente!',
    label_nome:        'Nome completo',
    placeholder_nome:  'Digite seu nome completo',
    label_email:       'E-mail (opcional)',
    placeholder_email: 'seuemail@exemplo.com',
    label_mensagem:    'Sua sugestão ou mensagem',
    placeholder_msg:   'Escreva sua sugestão aqui...',
    btn_enviar:        'Enviar Sugestão',
    form_sucesso:      'Sugestão enviada com sucesso! Obrigado pela sua contribuição.',
    form_erro_nome:    'Por favor, preencha seu nome.',
    form_erro_msg:     'Por favor, escreva sua mensagem.',
    rodape_titulo:     'Agrinho 2026',
    rodape_subtitulo:  'SENAR · Paraná',
    rodape_copy:       '© 2026 Concurso Agrinho — SENAR Paraná — Colégio Estadual Vinícius de Morais (PR). Projeto educativo sem fins lucrativos.',
    rodape_nav_sobre:       'Sobre',
    rodape_nav_tema:        'Tema',
    rodape_nav_tecnologias: 'Tecnologias',
    rodape_nav_video:       'Vídeo',
    rodape_nav_contato:     'Contato'
  },

  /* ---- INGLÊS --------------------------------------------- */
  en: {
    page_title:        'Agrinho 2026 — Strong Agro, Sustainable Future',
    label_idioma:      'Language:',
    label_visual:      'Visual:',
    label_texto:       'Text:',
    label_audio:       'Audio:',
    btn_colorido:      'Default',
    btn_branco:        'L/W',
    btn_preto:         'D/B',
    btn_narrar:        'Read Aloud',
    btn_parar:         'Stop Reading',
    logo_titulo:       'Agrinho 2026',
    logo_subtitulo:    'SENAR · Paraná',
    nav_sobre:         'About',
    nav_tema:          'Theme',
    nav_tecnologias:   'Technologies',
    nav_video:         'Video',
    nav_apoio:         'Support',
    nav_contato:       'Contact',
    hero_eyebrow:      'Agrinho Contest 2026',
    hero_titulo:       'Strong Agro,\nSustainable Future',
    hero_subtitulo:    'Balance between production and the environment',
    hero_btn_conhecer: 'Learn About the Project',
    hero_btn_apoiar:   'Support Now',
    sobre_eyebrow:     'The Program',
    sobre_titulo:      'What is Agrinho?',
    sobre_p1:          'The Agrinho Program is an initiative by SENAR Paraná that has existed for over 25 years, connecting rural and urban education through topics such as health, citizenship and, in this edition, agricultural sustainability.',
    sobre_p2:          'In 2026, the theme invites students to reflect on how Brazilian agribusiness can be economically strong without compromising natural resources for future generations. Technology, awareness and responsibility go hand in hand.',
    sobre_p3:          'This website was created as a participation project by Colégio Estadual Vinícius de Morais (PR), exploring concepts of sustainable production, technological innovation in agriculture and the role of every citizen in building a greener future.',
    estat_anos:        'Years of Program',
    estat_municipios:  'Participating Municipalities',
    estat_alunos:      'Students Impacted',
    tema_eyebrow:      'The Challenge',
    tema_titulo:       'Production and Nature in Balance',
    tema_intro:        'Brazil is one of the world\'s largest food producers. But how can we ensure this production respects the planet? Three pillars support this answer:',
    pilar1_titulo:     'Responsible Agriculture',
    pilar1_desc:       'Practices such as no-till farming, crop rotation and crop-livestock-forest integration reduce soil erosion, save water and increase productivity at the same time.',
    pilar2_titulo:     'Circular Economy',
    pilar2_desc:       'Agricultural waste such as straw and manure becomes energy, compost and biofertilizers. Nothing is lost: everything is transformed into more production with less environmental impact.',
    pilar3_titulo:     'Environmental Citizenship',
    pilar3_desc:       'The countryside needs guardians. From school, each student learns that consumer choices, proper waste disposal and preservation of springs are concrete acts of citizenship.',
    tec_eyebrow:       'Innovation in the Field',
    tec_titulo:        'Sustainable Technologies',
    tec_intro:         'The modern farmer has tools that once seemed like science fiction. See three examples already transforming Brazilian agriculture:',
    drone_credito:     'Photo: Pexels / Agricultural Drone Photo',
    drone_titulo:      'Precision Agriculture with Drones',
    drone_desc:        'Drones equipped with multispectral cameras fly over crops and identify areas with nutritional deficiencies, pests or water stress with centimeter precision. This allows the producer to apply inputs only where needed, reducing pesticide use by up to 40% and saving water and fuel. The result is healthier crops and a more preserved environment.',
    irri_credito:      'Photo: Pexels / Drip Irrigation Photo',
    irrigacao_titulo:  'Smart Drip Irrigation',
    irri_desc:         'The drip irrigation system delivers water directly to the plant root, drop by drop, controlled by soil moisture sensors connected to the internet. Sensors monitor each species water needs in real time and irrigate only when necessary. Compared to conventional sprinkler irrigation, smart drip saves up to 60% of water, a vital resource that is increasingly scarce on the planet.',
    solar_credito:     'Photo: Pexels / Rural Solar Energy Photo',
    solar_titulo:      'Rural Photovoltaic Solar Energy',
    solar_desc:        'Solar panels installed on rural properties generate clean electricity directly from the sun, eliminating or drastically reducing the energy bills of farms and homesteads. Surplus energy can be fed into the electrical grid, generating credits for the producer. With panel costs falling more than 80% in the last decade, solar energy has become one of the smartest and most sustainable investments for the 21st century Brazilian farmer.',
    video_eyebrow:     'Watch',
    video_titulo:      'The Field in Motion',
    video_intro:       'See the beauty and strength of sustainable agribusiness through the images below.',
    video_credito:     'Video by: Fernando Sanchez Aranguren (Pexels)',
    video_fallback:    'Your browser does not support HTML5 video playback.',
    apoio_eyebrow:     'Get Involved',
    apoio_titulo:      'Support This Project',
    apoio_intro:       'Do you believe in a more sustainable agro? Show your support by clicking below!',
    apoio_contador:    'This project has already received {N} endorsements!',
    apoio_carregando:  'Loading endorsements...',
    apoio_btn:         'Support Project',
    apoio_ja_feito:    'You have already registered your support. Thank you!',
    apoio_registrando: 'Registering endorsement...',
    apoio_erro:        'Could not register the endorsement. Please try again.',
    contato_eyebrow:   'Contact Us',
    contato_titulo:    'Leave Your Suggestion',
    contato_intro:     'Do you have an idea to make the project even better? Share it with us!',
    label_nome:        'Full name',
    placeholder_nome:  'Enter your full name',
    label_email:       'E-mail (optional)',
    placeholder_email: 'youremail@example.com',
    label_mensagem:    'Your suggestion or message',
    placeholder_msg:   'Write your suggestion here...',
    btn_enviar:        'Send Suggestion',
    form_sucesso:      'Suggestion sent successfully! Thank you for your contribution.',
    form_erro_nome:    'Please fill in your name.',
    form_erro_msg:     'Please write your message.',
    rodape_titulo:     'Agrinho 2026',
    rodape_subtitulo:  'SENAR · Paraná',
    rodape_copy:       '© 2026 Agrinho Contest — SENAR Paraná — Colégio Estadual Vinícius de Morais (PR). Non-profit educational project.',
    rodape_nav_sobre:       'About',
    rodape_nav_tema:        'Theme',
    rodape_nav_tecnologias: 'Technologies',
    rodape_nav_video:       'Video',
    rodape_nav_contato:     'Contact'
  },

  /* ---- ESPANHOL ------------------------------------------- */
  es: {
    page_title:        'Agrinho 2026 — Agro fuerte, futuro sostenible',
    label_idioma:      'Idioma:',
    label_visual:      'Visual:',
    label_texto:       'Texto:',
    label_audio:       'Audio:',
    btn_colorido:      'Estándar',
    btn_branco:        'L/W',
    btn_preto:         'D/B',
    btn_narrar:        'Narrar Sitio',
    btn_parar:         'Detener Narración',
    logo_titulo:       'Agrinho 2026',
    logo_subtitulo:    'SENAR · Paraná',
    nav_sobre:         'Acerca de',
    nav_tema:          'Tema',
    nav_tecnologias:   'Tecnologías',
    nav_video:         'Video',
    nav_apoio:         'Apoyar',
    nav_contato:       'Contacto',
    hero_eyebrow:      'Concurso Agrinho 2026',
    hero_titulo:       'Agro fuerte,\nfuturo sostenible',
    hero_subtitulo:    'Equilibrio entre producción y medio ambiente',
    hero_btn_conhecer: 'Conocer el Proyecto',
    hero_btn_apoiar:   'Apoyar Ahora',
    sobre_eyebrow:     'El Programa',
    sobre_titulo:      '¿Qué es Agrinho?',
    sobre_p1:          'El Programa Agrinho es una iniciativa de SENAR Paraná que existe desde hace más de 25 años, conectando la educación del campo y la ciudad a través de temas como salud, ciudadanía y, en esta edición, sostenibilidad agrícola.',
    sobre_p2:          'En 2026, el tema invita a los estudiantes a reflexionar sobre cómo el agronegocio brasileño puede ser económicamente fuerte sin comprometer los recursos naturales para las próximas generaciones. Tecnología, conciencia y responsabilidad van de la mano.',
    sobre_p3:          'Este sitio fue creado como proyecto de participación del Colégio Estadual Vinícius de Morais (PR), explorando conceptos de producción sostenible, innovación tecnológica en el campo y el papel de cada ciudadano en la construcción de un futuro más verde.',
    estat_anos:        'Años de Programa',
    estat_municipios:  'Municipios Participantes',
    estat_alunos:      'Alumnos Impactados',
    tema_eyebrow:      'El Desafío',
    tema_titulo:       'Producción y Naturaleza en Equilibrio',
    tema_intro:        'Brasil es uno de los mayores productores de alimentos del mundo. Pero, ¿cómo garantizar que esa producción respete el planeta? Tres pilares sostienen esta respuesta:',
    pilar1_titulo:     'Agropecuaria Responsable',
    pilar1_desc:       'Prácticas como la siembra directa, la rotación de cultivos y la integración cultivo-ganadería-forestal reducen la erosión del suelo, ahorran agua y aumentan la productividad al mismo tiempo.',
    pilar2_titulo:     'Economía Circular',
    pilar2_desc:       'Los residuos agrícolas como la paja y el estiércol se convierten en energía,
